version: "3"
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python3.7 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: portfolio.env
    ports:
      - "8000:8000"