version: "3"
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py collectstatic --no-input --clear && gunicorn portfolio.wsgi:application -c gunicorn.conf.py"
    volumes:
      - .:/code
    env_file: portfolio.env
    ports:
      - "8000:8000"