version: "3"
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn portfolio.wsgi:application -c gunicorn.conf.py
    volumes:
      - .:/code
    env_file: portfolio.env
    ports:
      - "8000:8000"